// Autogenerated code. Don't touch.
namespace RapeEngine.Maker {
	partial class MainForm {
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		//private System.ComponentModel.IContainer components;
		private System.Windows.Forms.GroupBox groupBox1;
		private System.Windows.Forms.GroupBox groupBox2;
		private System.Windows.Forms.TreeView actions_tree;
		private System.Windows.Forms.ListBox scripts_list;
		private System.Windows.Forms.Button button_vars;
		
		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">True if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing) {
			if (disposing) {
				/*if (components != null) {
					components.Dispose();
				}*/
			}
			base.Dispose(disposing);
		}
		
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent() {
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.scripts_list = new System.Windows.Forms.ListBox();
			this.groupBox2 = new System.Windows.Forms.GroupBox();
			this.button_vars = new System.Windows.Forms.Button();
			this.actions_tree = new System.Windows.Forms.TreeView();
			this.groupBox1.SuspendLayout();
			this.groupBox2.SuspendLayout();
			this.SuspendLayout();
			// 
			// groupBox1
			// 
			this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
			| System.Windows.Forms.AnchorStyles.Left)));
			this.groupBox1.Controls.Add(this.scripts_list);
			this.groupBox1.Location = new System.Drawing.Point(12, 12);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(200, 707);
			this.groupBox1.TabIndex = 0;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "Scripts";
			// 
			// scripts_list
			// 
			this.scripts_list.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
			| System.Windows.Forms.AnchorStyles.Left)));
			this.scripts_list.FormattingEnabled = true;
			this.scripts_list.Location = new System.Drawing.Point(6, 19);
			this.scripts_list.Name = "scripts_list";
			this.scripts_list.Size = new System.Drawing.Size(188, 667);
			this.scripts_list.TabIndex = 0;
			this.scripts_list.SelectedValueChanged += new System.EventHandler(this.Scripts_listSelectedValueChanged);
			// 
			// groupBox2
			// 
			this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
			| System.Windows.Forms.AnchorStyles.Left) 
			| System.Windows.Forms.AnchorStyles.Right)));
			this.groupBox2.Controls.Add(this.button_vars);
			this.groupBox2.Controls.Add(this.actions_tree);
			this.groupBox2.Location = new System.Drawing.Point(218, 12);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new System.Drawing.Size(1050, 696);
			this.groupBox2.TabIndex = 1;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "Script Editor";
			// 
			// button_vars
			// 
			this.button_vars.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
			this.button_vars.Location = new System.Drawing.Point(932, 663);
			this.button_vars.Name = "button_vars";
			this.button_vars.Size = new System.Drawing.Size(112, 23);
			this.button_vars.TabIndex = 1;
			this.button_vars.Text = "Flags and Variables";
			this.button_vars.UseVisualStyleBackColor = true;
			this.button_vars.Click += new System.EventHandler(this.Button_varsClick);
			// 
			// actions_tree
			// 
			this.actions_tree.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
			| System.Windows.Forms.AnchorStyles.Left) 
			| System.Windows.Forms.AnchorStyles.Right)));
			this.actions_tree.Location = new System.Drawing.Point(6, 19);
			this.actions_tree.Name = "actions_tree";
			this.actions_tree.Size = new System.Drawing.Size(1038, 638);
			this.actions_tree.TabIndex = 0;
			this.actions_tree.NodeMouseDoubleClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.Actions_treeNodeMouseDoubleClick);
			this.actions_tree.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Actions_treeKeyDown);
			// 
			// MainForm
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(1280, 720);
			this.Controls.Add(this.groupBox2);
			this.Controls.Add(this.groupBox1);
			this.Icon = global::RapeEngine.Resources.Resources.erbetie;
			this.Name = "MainForm";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Rape Maker";
			this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
			this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.MainFormFormClosed);
			this.groupBox1.ResumeLayout(false);
			this.groupBox2.ResumeLayout(false);
			this.ResumeLayout(false);

		}
	}
}
