// Autogenerated code. Don't touch.
namespace RapeEngine.Maker
{
	partial class VarFlagForm
	{
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.LinkLabel flag;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.RadioButton switch_true;
		private System.Windows.Forms.RadioButton switch_false;
		private System.Windows.Forms.Button button_cancel;
		private System.Windows.Forms.Button button_ok;
		
		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing) {
				if (components != null) {
					components.Dispose();
				}
			}
			base.Dispose(disposing);
		}
		
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent()
		{
			this.label1 = new System.Windows.Forms.Label();
			this.flag = new System.Windows.Forms.LinkLabel();
			this.label2 = new System.Windows.Forms.Label();
			this.switch_true = new System.Windows.Forms.RadioButton();
			this.switch_false = new System.Windows.Forms.RadioButton();
			this.button_cancel = new System.Windows.Forms.Button();
			this.button_ok = new System.Windows.Forms.Button();
			this.SuspendLayout();
			// 
			// label1
			// 
			this.label1.Location = new System.Drawing.Point(12, 9);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(151, 23);
			this.label1.TabIndex = 0;
			this.label1.Text = "label1";
			// 
			// flag
			// 
			this.flag.Location = new System.Drawing.Point(169, 9);
			this.flag.Name = "flag";
			this.flag.Size = new System.Drawing.Size(100, 23);
			this.flag.TabIndex = 1;
			this.flag.TabStop = true;
			this.flag.Text = "linkLabel1";
			this.flag.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.FlagLinkClicked);
			// 
			// label2
			// 
			this.label2.Location = new System.Drawing.Point(12, 41);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(90, 23);
			this.label2.TabIndex = 2;
			this.label2.Text = "label2";
			// 
			// switch_true
			// 
			this.switch_true.Location = new System.Drawing.Point(158, 35);
			this.switch_true.Name = "switch_true";
			this.switch_true.Size = new System.Drawing.Size(55, 24);
			this.switch_true.TabIndex = 3;
			this.switch_true.TabStop = true;
			this.switch_true.Text = "True";
			this.switch_true.UseVisualStyleBackColor = true;
			// 
			// switch_false
			// 
			this.switch_false.Location = new System.Drawing.Point(219, 35);
			this.switch_false.Name = "switch_false";
			this.switch_false.Size = new System.Drawing.Size(50, 24);
			this.switch_false.TabIndex = 4;
			this.switch_false.TabStop = true;
			this.switch_false.Text = "False";
			this.switch_false.UseVisualStyleBackColor = true;
			// 
			// button_cancel
			// 
			this.button_cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
			this.button_cancel.Location = new System.Drawing.Point(194, 85);
			this.button_cancel.Name = "button_cancel";
			this.button_cancel.Size = new System.Drawing.Size(75, 23);
			this.button_cancel.TabIndex = 5;
			this.button_cancel.Text = "Cancel";
			this.button_cancel.UseVisualStyleBackColor = true;
			// 
			// button_ok
			// 
			this.button_ok.DialogResult = System.Windows.Forms.DialogResult.OK;
			this.button_ok.Location = new System.Drawing.Point(113, 85);
			this.button_ok.Name = "button_ok";
			this.button_ok.Size = new System.Drawing.Size(75, 23);
			this.button_ok.TabIndex = 6;
			this.button_ok.Text = "OK";
			this.button_ok.UseVisualStyleBackColor = true;
			// 
			// VarFlagForm
			// 
			this.AcceptButton = this.button_ok;
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.CancelButton = this.button_cancel;
			this.ClientSize = new System.Drawing.Size(277, 126);
			this.ControlBox = false;
			this.Controls.Add(this.button_ok);
			this.Controls.Add(this.button_cancel);
			this.Controls.Add(this.switch_false);
			this.Controls.Add(this.switch_true);
			this.Controls.Add(this.label2);
			this.Controls.Add(this.flag);
			this.Controls.Add(this.label1);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.Name = "VarFlagForm";
			this.ShowInTaskbar = false;
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Flag Setup";
			this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.VarFlagFormFormClosed);
			this.ResumeLayout(false);

		}
	}
}
