// Autogenerated code. Don't touch.
namespace RapeEngine.Maker
{
	partial class VariablesForm
	{
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		private System.Windows.Forms.ListBox flags_list_group;
		private System.Windows.Forms.TabPage tab_flags;
		private System.Windows.Forms.GroupBox groupBox1;
		private System.Windows.Forms.TextBox flag_name;
		private System.Windows.Forms.ListBox flags_list_item;
		private System.Windows.Forms.TabPage tab_vars;
		private System.Windows.Forms.Button button_close;
		private System.Windows.Forms.GroupBox groupBox2;
		private System.Windows.Forms.TextBox var_name;
		private System.Windows.Forms.ListBox vars_list_item;
		private System.Windows.Forms.ListBox vars_list_group;
		private System.Windows.Forms.Button button_ok;
		private System.Windows.Forms.TabControl tabs;
		
		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing) {
				if (components != null) {
					components.Dispose();
				}
			}
			base.Dispose(disposing);
		}
		
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent()
		{
			this.flags_list_group = new System.Windows.Forms.ListBox();
			this.tabs = new System.Windows.Forms.TabControl();
			this.tab_flags = new System.Windows.Forms.TabPage();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.flag_name = new System.Windows.Forms.TextBox();
			this.flags_list_item = new System.Windows.Forms.ListBox();
			this.tab_vars = new System.Windows.Forms.TabPage();
			this.groupBox2 = new System.Windows.Forms.GroupBox();
			this.var_name = new System.Windows.Forms.TextBox();
			this.vars_list_item = new System.Windows.Forms.ListBox();
			this.vars_list_group = new System.Windows.Forms.ListBox();
			this.button_close = new System.Windows.Forms.Button();
			this.button_ok = new System.Windows.Forms.Button();
			this.tabs.SuspendLayout();
			this.tab_flags.SuspendLayout();
			this.groupBox1.SuspendLayout();
			this.tab_vars.SuspendLayout();
			this.groupBox2.SuspendLayout();
			this.SuspendLayout();
			// 
			// flags_list_group
			// 
			this.flags_list_group.Font = new System.Drawing.Font("Courier New", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.flags_list_group.FormattingEnabled = true;
			this.flags_list_group.ItemHeight = 14;
			this.flags_list_group.Location = new System.Drawing.Point(6, 6);
			this.flags_list_group.Name = "flags_list_group";
			this.flags_list_group.Size = new System.Drawing.Size(105, 340);
			this.flags_list_group.TabIndex = 0;
			this.flags_list_group.SelectedIndexChanged += new System.EventHandler(this.Flags_list_groupSelectedIndexChanged);
			// 
			// tabs
			// 
			this.tabs.Controls.Add(this.tab_flags);
			this.tabs.Controls.Add(this.tab_vars);
			this.tabs.Location = new System.Drawing.Point(12, 12);
			this.tabs.Name = "tabs";
			this.tabs.SelectedIndex = 0;
			this.tabs.Size = new System.Drawing.Size(409, 392);
			this.tabs.TabIndex = 1;
			// 
			// tab_flags
			// 
			this.tab_flags.Controls.Add(this.groupBox1);
			this.tab_flags.Controls.Add(this.flags_list_item);
			this.tab_flags.Controls.Add(this.flags_list_group);
			this.tab_flags.Location = new System.Drawing.Point(4, 22);
			this.tab_flags.Name = "tab_flags";
			this.tab_flags.Padding = new System.Windows.Forms.Padding(3);
			this.tab_flags.Size = new System.Drawing.Size(401, 366);
			this.tab_flags.TabIndex = 0;
			this.tab_flags.Text = "Flags";
			this.tab_flags.UseVisualStyleBackColor = true;
			// 
			// groupBox1
			// 
			this.groupBox1.Controls.Add(this.flag_name);
			this.groupBox1.Location = new System.Drawing.Point(123, 298);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(272, 48);
			this.groupBox1.TabIndex = 2;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "Name";
			// 
			// flag_name
			// 
			this.flag_name.Location = new System.Drawing.Point(6, 22);
			this.flag_name.Name = "flag_name";
			this.flag_name.Size = new System.Drawing.Size(260, 20);
			this.flag_name.TabIndex = 3;
			this.flag_name.TextChanged += new System.EventHandler(this.Flag_nameTextChanged);
			// 
			// flags_list_item
			// 
			this.flags_list_item.Font = new System.Drawing.Font("Courier New", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.flags_list_item.FormattingEnabled = true;
			this.flags_list_item.ItemHeight = 14;
			this.flags_list_item.Location = new System.Drawing.Point(117, 6);
			this.flags_list_item.Name = "flags_list_item";
			this.flags_list_item.Size = new System.Drawing.Size(272, 284);
			this.flags_list_item.TabIndex = 1;
			this.flags_list_item.SelectedIndexChanged += new System.EventHandler(this.Flags_list_itemSelectedIndexChanged);
			// 
			// tab_vars
			// 
			this.tab_vars.Controls.Add(this.groupBox2);
			this.tab_vars.Controls.Add(this.vars_list_item);
			this.tab_vars.Controls.Add(this.vars_list_group);
			this.tab_vars.Location = new System.Drawing.Point(4, 22);
			this.tab_vars.Name = "tab_vars";
			this.tab_vars.Padding = new System.Windows.Forms.Padding(3);
			this.tab_vars.Size = new System.Drawing.Size(401, 366);
			this.tab_vars.TabIndex = 1;
			this.tab_vars.Text = "Variables";
			this.tab_vars.UseVisualStyleBackColor = true;
			// 
			// groupBox2
			// 
			this.groupBox2.Controls.Add(this.var_name);
			this.groupBox2.Location = new System.Drawing.Point(123, 298);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new System.Drawing.Size(272, 48);
			this.groupBox2.TabIndex = 3;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "Name";
			// 
			// var_name
			// 
			this.var_name.Location = new System.Drawing.Point(6, 22);
			this.var_name.Name = "var_name";
			this.var_name.Size = new System.Drawing.Size(260, 20);
			this.var_name.TabIndex = 3;
			this.var_name.TextChanged += new System.EventHandler(this.Var_nameTextChanged);
			// 
			// vars_list_item
			// 
			this.vars_list_item.Font = new System.Drawing.Font("Courier New", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.vars_list_item.FormattingEnabled = true;
			this.vars_list_item.ItemHeight = 14;
			this.vars_list_item.Location = new System.Drawing.Point(117, 6);
			this.vars_list_item.Name = "vars_list_item";
			this.vars_list_item.Size = new System.Drawing.Size(272, 284);
			this.vars_list_item.TabIndex = 3;
			this.vars_list_item.SelectedIndexChanged += new System.EventHandler(this.Vars_list_itemSelectedIndexChanged);
			// 
			// vars_list_group
			// 
			this.vars_list_group.Font = new System.Drawing.Font("Courier New", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.vars_list_group.FormattingEnabled = true;
			this.vars_list_group.ItemHeight = 14;
			this.vars_list_group.Location = new System.Drawing.Point(6, 6);
			this.vars_list_group.Name = "vars_list_group";
			this.vars_list_group.Size = new System.Drawing.Size(105, 340);
			this.vars_list_group.TabIndex = 3;
			this.vars_list_group.SelectedIndexChanged += new System.EventHandler(this.Vars_list_groupSelectedIndexChanged);
			// 
			// button_close
			// 
			this.button_close.DialogResult = System.Windows.Forms.DialogResult.Cancel;
			this.button_close.Location = new System.Drawing.Point(346, 410);
			this.button_close.Name = "button_close";
			this.button_close.Size = new System.Drawing.Size(75, 23);
			this.button_close.TabIndex = 2;
			this.button_close.Text = "Cancel";
			this.button_close.UseVisualStyleBackColor = true;
			// 
			// button_ok
			// 
			this.button_ok.DialogResult = System.Windows.Forms.DialogResult.OK;
			this.button_ok.Location = new System.Drawing.Point(265, 411);
			this.button_ok.Name = "button_ok";
			this.button_ok.Size = new System.Drawing.Size(75, 23);
			this.button_ok.TabIndex = 3;
			this.button_ok.Text = "OK";
			this.button_ok.UseVisualStyleBackColor = true;
			// 
			// VariablesForm
			// 
			this.AcceptButton = this.button_ok;
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.CancelButton = this.button_close;
			this.ClientSize = new System.Drawing.Size(430, 446);
			this.ControlBox = false;
			this.Controls.Add(this.button_ok);
			this.Controls.Add(this.button_close);
			this.Controls.Add(this.tabs);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.Name = "VariablesForm";
			this.ShowInTaskbar = false;
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Variables";
			this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.VariablesFormFormClosed);
			this.tabs.ResumeLayout(false);
			this.tab_flags.ResumeLayout(false);
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			this.tab_vars.ResumeLayout(false);
			this.groupBox2.ResumeLayout(false);
			this.groupBox2.PerformLayout();
			this.ResumeLayout(false);

		}
	}
}
